// VULMS automation library — Puppeteer-based for Railway/Docker deployment
// Uses real browser to handle reCAPTCHA v3 and ASP.NET WebForms postbacks
// All navigation done through Puppeteer clicks (no direct URLs work with ASP.NET)

import * as cheerio from 'cheerio';

const VULMS_BASE = 'https://vulms.vu.edu.pk';
const VULMS_LOGIN = 'https://vulms.vu.edu.pk/';

export interface VULMSCookie {
  name: string;
  value: string;
  domain: string;
  path: string;
  expires: number;
  httpOnly: boolean;
  secure: boolean;
  sameSite: string;
}

export interface SubjectInfo {
  name: string;
  code: string;
  url: string;
}

export interface HandoutInfo {
  name: string;
  url: string;
  type: string;
}

// ─── PUPPETEER LOGIN ────────────────────────────────────────────────────────

async function getPuppeteer() {
  try {
    return await import('puppeteer');
  } catch {
    return null;
  }
}

function getChromePath(): string {
  if (process.env.PUPPETEER_EXECUTABLE_PATH) return process.env.PUPPETEER_EXECUTABLE_PATH;
  if (process.env.CHROME_PATH) return process.env.CHROME_PATH;
  return '/usr/bin/chromium';
}

const BROWSER_ARGS = [
  '--no-sandbox',
  '--disable-setuid-sandbox',
  '--disable-dev-shm-usage',
  '--disable-gpu',
  '--window-size=1280,720',
  '--disable-blink-features=AutomationControlled',
  '--disable-extensions',
  '--disable-component-update',
  '--disable-default-apps',
  '--disable-background-networking',
];

// Main login function
export async function loginToVULMS(studentId: string, password: string, _recaptchaToken: string = '') {
  const puppeteerModule = await getPuppeteer();
  if (!puppeteerModule) {
    throw new Error('Puppeteer is not available. Please deploy on Railway with Docker support.');
  }

  console.log('[VULMS] Using Puppeteer login for:', studentId);
  const puppeteer = puppeteerModule;
  const executablePath = getChromePath();

  const browser = await puppeteer.default.launch({
    headless: true,
    executablePath,
    args: BROWSER_ARGS,
    ignoreDefaultArgs: ['--disable-extensions'],
  });

  const page = await browser.newPage();

  try {
    await page.setViewport({ width: 1280, height: 720 });
    await page.setUserAgent(
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    );

    // Stealth
    await page.evaluateOnNewDocument(() => {
      Object.defineProperty(navigator, 'webdriver', { get: () => false });
      Object.defineProperty(navigator, 'plugins', { get: () => [1, 2, 3, 4, 5] });
      Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en', 'ur'] });
      (window as Record<string, unknown>).chrome = { runtime: {} };
    });

    // Navigate to VULMS login
    console.log('[VULMS] Loading login page...');
    await page.goto(VULMS_LOGIN, { waitUntil: 'networkidle2', timeout: 45000 });
    await page.waitForSelector('#txtStudentID', { timeout: 15000 });

    // Wait for reCAPTCHA v3 token (auto-generated by page)
    console.log('[VULMS] Waiting for reCAPTCHA token...');
    await page.waitForFunction(
      () => {
        const field = document.querySelector('#g-recaptcha-response') as HTMLTextAreaElement;
        return field && field.value && field.value.length > 10;
      },
      { timeout: 15000 }
    ).catch(() => console.log('[VULMS] reCAPTCHA token not found, proceeding anyway'));

    await new Promise(r => setTimeout(r, 500 + Math.random() * 1000));

    // Fill credentials
    await page.click('#txtStudentID', { clickCount: 3 });
    await page.type('#txtStudentID', studentId, { delay: 40 + Math.random() * 60 });
    await new Promise(r => setTimeout(r, 300 + Math.random() * 500));

    await page.click('#txtPassword', { clickCount: 3 });
    await page.type('#txtPassword', password, { delay: 40 + Math.random() * 60 });
    await new Promise(r => setTimeout(r, 500 + Math.random() * 1000));

    // Click Sign In
    console.log('[VULMS] Clicking Sign In...');
    await Promise.all([
      page.click('#ibtnLogin'),
      page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 30000 }),
    ]).catch(async () => {
      await page.evaluate(() => {
        const form = document.querySelector('#ctl00') as HTMLFormElement;
        if (form) form.submit();
      });
      await page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 30000 }).catch(() => {});
    });

    // Check if login successful
    const currentUrl = page.url();
    const pageContent = await page.content();
    const stillOnLoginPage = pageContent.includes('txtStudentID') && pageContent.includes('txtPassword');

    if (stillOnLoginPage) {
      const errorMsg = await page.evaluate(() => {
        const el = document.querySelector('#lblError');
        return el ? el.textContent?.trim() : '';
      });
      await browser.close();
      throw new Error(errorMsg || 'Login failed. Please check your Student ID and Password.');
    }

    console.log('[VULMS] Login successful! URL:', currentUrl);

    // Get session cookies
    const cookies = await page.cookies();

    // Navigate to dashboard if needed
    if (!currentUrl.toLowerCase().includes('home.aspx')) {
      console.log('[VULMS] Navigating to Home...');
      await page.goto(`${VULMS_BASE}/Home.aspx`, { waitUntil: 'networkidle2', timeout: 30000 });
    }

    // ── SCRAPE SUBJECTS ──
    console.log('[VULMS] Scraping subjects...');
    const subjects = await page.evaluate(() => {
      const results: Array<{ name: string; code: string; eventTarget: string }> = [];
      const seen = new Set<string>();

      // VULMS uses GridView with ibtnCourseHome links
      const courseLinks = document.querySelectorAll('a[href*="ibtnCourseHome"]');
      courseLinks.forEach((el) => {
        const link = el as HTMLAnchorElement;
        const text = link.textContent?.trim().replace(/\s+/g, ' ') || '';
        const href = link.getAttribute('href') || '';

        // Extract subject code (e.g. ECO402, MGMT627)
        const codeMatch = text.match(/([A-Z]{2,4}\d{3}[A-Z]?)/i);
        const code = codeMatch ? codeMatch[1].toUpperCase() : '';

        // Skip instructor names and empty links
        if (!code || code.length < 4) return;
        if (seen.has(code)) return;
        seen.add(code);

        // Extract the postback event target
        const match = href.match(/__doPostBack\('([^']+)'/);
        const eventTarget = match ? match[1] : '';

        if (eventTarget) {
          results.push({ name: text, code, eventTarget });
        }
      });

      return results;
    });

    console.log('[VULMS] Found subjects:', subjects.length, subjects.map(s => s.code));

    // For each subject, we need to navigate and get the lesson list
    // But we'll return subjects first and let the frontend request lessons separately
    // Store eventTarget in the URL field for later use
    const formattedSubjects: SubjectInfo[] = subjects.map(s => ({
      name: s.name,
      code: s.code,
      url: s.eventTarget, // We use eventTarget as the "URL" to navigate later
    }));

    await browser.close();

    return {
      success: true,
      cookies: cookies.map(c => ({
        name: c.name,
        value: c.value,
        domain: c.domain || 'vulms.vu.edu.pk',
        path: c.path || '/',
      })),
      subjects: formattedSubjects,
      browser: null,
    };
  } catch (error) {
    await browser.close().catch(() => {});
    throw error;
  }
}

// ── GET HANDOUTS FOR A SUBJECT ──
// This needs to login again with Puppeteer, navigate to the course, and scrape lessons
export async function getHandouts(
  cookies: Array<{ name: string; value: string; domain?: string; path?: string }>,
  courseEventTarget: string
) {
  const puppeteerModule = await getPuppeteer();
  if (!puppeteerModule) {
    return []; // Fallback: no handouts without Puppeteer
  }

  const puppeteer = puppeteerModule;
  const executablePath = getChromePath();

  const browser = await puppeteer.default.launch({
    headless: true,
    executablePath,
    args: BROWSER_ARGS,
    ignoreDefaultArgs: ['--disable-extensions'],
  });

  const page = await browser.newPage();

  try {
    await page.setViewport({ width: 1280, height: 720 });
    await page.setUserAgent(
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    );

    // Set cookies from login session
    await page.setCookie(...cookies.map(c => ({
      name: c.name,
      value: c.value,
      domain: c.domain || 'vulms.vu.edu.pk',
      path: c.path || '/',
    })));

    // Navigate to VULMS dashboard
    console.log('[VULMS Handouts] Loading dashboard...');
    await page.goto(`${VULMS_BASE}/Home.aspx`, { waitUntil: 'networkidle2', timeout: 45000 });

    // Check if session is still valid
    if (page.url().includes('Login') || (await page.content()).includes('txtStudentID')) {
      await browser.close();
      throw new Error('Session expired. Please login again.');
    }

    // Click on the course using postback
    console.log('[VULMS Handouts] Navigating to course:', courseEventTarget);
    await page.evaluate((target) => {
      (window as Record<string, unknown>).__doPostBack(target, '');
    }, courseEventTarget);

    await page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 30000 }).catch(() => {});
    console.log('[VULMS Handouts] Course page URL:', page.url());

    // Scrape lesson/handout links from the course page
    const lessons = await page.evaluate(() => {
      const results: Array<{ name: string; eventTarget: string; type: string }> = [];
      const seen = new Set<string>();

      // VULMS uses lstWeeklySchedule > rptIndex > lbtnViewLesson pattern
      const lessonLinks = document.querySelectorAll('a[href*="lbtnViewLesson"]');
      lessonLinks.forEach((el) => {
        const link = el as HTMLAnchorElement;
        const text = link.textContent?.trim().replace(/\s+/g, ' ') || '';
        const href = link.getAttribute('href') || '';

        if (!text || seen.has(text)) return;
        seen.add(text);

        const match = href.match(/__doPostBack\('([^']+)'/);
        const eventTarget = match ? match[1] : '';

        if (eventTarget) {
          results.push({ name: text, eventTarget, type: 'lesson' });
        }
      });

      return results;
    });

    console.log('[VULMS Handouts] Found lessons:', lessons.length);

    // Format as HandoutInfo — we store eventTarget in URL field
    const handouts: HandoutInfo[] = lessons.map(l => ({
      name: l.name,
      url: l.eventTarget, // eventTarget stored here for later use
      type: l.type,
    }));

    await browser.close();
    return handouts;
  } catch (error) {
    await browser.close().catch(() => {});
    console.error('[VULMS Handouts] Error:', error instanceof Error ? error.message : error);
    return [];
  }
}

// ── GET SUBJECTS (re-scan with existing cookies) ──
export async function getSubjects(cookies: Array<{ name: string; value: string; domain?: string; path?: string }>) {
  const puppeteerModule = await getPuppeteer();
  if (!puppeteerModule) return [];

  const puppeteer = puppeteerModule;
  const executablePath = getChromePath();

  const browser = await puppeteer.default.launch({
    headless: true, executablePath, args: BROWSER_ARGS,
    ignoreDefaultArgs: ['--disable-extensions'],
  });

  const page = await browser.newPage();

  try {
    await page.setViewport({ width: 1280, height: 720 });
    await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36');
    await page.setCookie(...cookies.map(c => ({
      name: c.name, value: c.value,
      domain: c.domain || 'vulms.vu.edu.pk', path: c.path || '/',
    })));

    await page.goto(`${VULMS_BASE}/Home.aspx`, { waitUntil: 'networkidle2', timeout: 45000 });

    if (page.url().includes('Login') || (await page.content()).includes('txtStudentID')) {
      await browser.close();
      throw new Error('Session expired. Please login again.');
    }

    const subjects = await page.evaluate(() => {
      const results: Array<{ name: string; code: string; eventTarget: string }> = [];
      const seen = new Set<string>();
      const courseLinks = document.querySelectorAll('a[href*="ibtnCourseHome"]');
      courseLinks.forEach((el) => {
        const link = el as HTMLAnchorElement;
        const text = link.textContent?.trim().replace(/\s+/g, ' ') || '';
        const href = link.getAttribute('href') || '';
        const codeMatch = text.match(/([A-Z]{2,4}\d{3}[A-Z]?)/i);
        const code = codeMatch ? codeMatch[1].toUpperCase() : '';
        if (!code || code.length < 4 || seen.has(code)) return;
        seen.add(code);
        const match = href.match(/__doPostBack\('([^']+)'/);
        const eventTarget = match ? match[1] : '';
        if (eventTarget) results.push({ name: text, code, eventTarget });
      });
      return results;
    });

    await browser.close();
    return subjects.map(s => ({ name: s.name, code: s.code, url: s.eventTarget }));
  } catch (error) {
    await browser.close().catch(() => {});
    throw error;
  }
}

// ── DOWNLOAD HANDOUT CONTENT ──
// Navigate to a lesson page and extract text content
export async function downloadHandoutContent(
  cookies: Array<{ name: string; value: string; domain?: string; path?: string }>,
  lessonEventTarget: string
) {
  const puppeteerModule = await getPuppeteer();
  if (!puppeteerModule) {
    return 'Content not available without browser support.';
  }

  const puppeteer = puppeteerModule;
  const executablePath = getChromePath();

  const browser = await puppeteer.default.launch({
    headless: true, executablePath, args: BROWSER_ARGS,
    ignoreDefaultArgs: ['--disable-extensions'],
  });

  const page = await browser.newPage();

  try {
    await page.setViewport({ width: 1280, height: 720 });
    await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36');
    await page.setCookie(...cookies.map(c => ({
      name: c.name, value: c.value,
      domain: c.domain || 'vulms.vu.edu.pk', path: c.path || '/',
    })));

    // We need to be on the CourseHome page first, then click the lesson
    // Navigate to the course page (we need the course event target)
    // For now, navigate to dashboard first
    await page.goto(`${VULMS_BASE}/Home.aspx`, { waitUntil: 'networkidle2', timeout: 45000 });

    // Click the lesson using postback
    console.log('[VULMS Content] Opening lesson:', lessonEventTarget);
    await page.evaluate((target) => {
      (window as Record<string, unknown>).__doPostBack(target, '');
    }, lessonEventTarget);

    await page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 30000 }).catch(() => {});

    // Extract content from the lesson page
    const content = await page.evaluate(() => {
      // Try multiple content selectors
      const selectors = [
        '#MainContent',
        '.m-portlet__body',
        '.content-area',
        '#ContentPlaceHolder1',
        'main',
        '.portlet-body',
      ];

      for (const sel of selectors) {
        const el = document.querySelector(sel);
        if (el && el.textContent && el.textContent.trim().length > 100) {
          return el.textContent.trim();
        }
      }

      return document.body.textContent?.trim() || 'Content not available.';
    });

    await browser.close();
    return content.replace(/\s+/g, ' ').trim();
  } catch (error) {
    await browser.close().catch(() => {});
    console.error('[VULMS Content] Error:', error instanceof Error ? error.message : error);
    return 'Failed to load content. Please try again.';
  }
}
